global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.5
  publish_frequency: 0.4
  static_map: true
  resolution: 0.1
  transform_tolerance: 0.5
  always_send_full_costmap: false
  
