// Generated by gencpp from file neo_kinematics_omnidrive/HomingRequest.msg
// DO NOT EDIT!


#ifndef NEO_KINEMATICS_OMNIDRIVE_MESSAGE_HOMINGREQUEST_H
#define NEO_KINEMATICS_OMNIDRIVE_MESSAGE_HOMINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neo_kinematics_omnidrive
{
template <class ContainerAllocator>
struct HomingRequest_
{
  typedef HomingRequest_<ContainerAllocator> Type;

  HomingRequest_()
    {
    }
  HomingRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HomingRequest_

typedef ::neo_kinematics_omnidrive::HomingRequest_<std::allocator<void> > HomingRequest;

typedef boost::shared_ptr< ::neo_kinematics_omnidrive::HomingRequest > HomingRequestPtr;
typedef boost::shared_ptr< ::neo_kinematics_omnidrive::HomingRequest const> HomingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_kinematics_omnidrive

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_kinematics_omnidrive/HomingRequest";
  }

  static const char* value(const ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HomingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::neo_kinematics_omnidrive::HomingRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NEO_KINEMATICS_OMNIDRIVE_MESSAGE_HOMINGREQUEST_H
