// Generated by gencpp from file neo_kinematics_omnidrive/HomingResponse.msg
// DO NOT EDIT!


#ifndef NEO_KINEMATICS_OMNIDRIVE_MESSAGE_HOMINGRESPONSE_H
#define NEO_KINEMATICS_OMNIDRIVE_MESSAGE_HOMINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace neo_kinematics_omnidrive
{
template <class ContainerAllocator>
struct HomingResponse_
{
  typedef HomingResponse_<ContainerAllocator> Type;

  HomingResponse_()
    : success()  {
    }
  HomingResponse_(const ContainerAllocator& _alloc)
    : success(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HomingResponse_

typedef ::neo_kinematics_omnidrive::HomingResponse_<std::allocator<void> > HomingResponse;

typedef boost::shared_ptr< ::neo_kinematics_omnidrive::HomingResponse > HomingResponsePtr;
typedef boost::shared_ptr< ::neo_kinematics_omnidrive::HomingResponse const> HomingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_kinematics_omnidrive

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f31cb2e813cfb0e488c574c3b5d9dbe";
  }

  static const char* value(const ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f31cb2e813cfb0eULL;
  static const uint64_t static_value2 = 0x488c574c3b5d9dbeULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_kinematics_omnidrive/HomingResponse";
  }

  static const char* value(const ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool success\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HomingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_kinematics_omnidrive::HomingResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_KINEMATICS_OMNIDRIVE_MESSAGE_HOMINGRESPONSE_H
