// Generated by gencpp from file neo_kinematics_omnidrive/Homing.msg
// DO NOT EDIT!


#ifndef NEO_KINEMATICS_OMNIDRIVE_MESSAGE_HOMING_H
#define NEO_KINEMATICS_OMNIDRIVE_MESSAGE_HOMING_H

#include <ros/service_traits.h>


#include <neo_kinematics_omnidrive/HomingRequest.h>
#include <neo_kinematics_omnidrive/HomingResponse.h>


namespace neo_kinematics_omnidrive
{

struct Homing
{

typedef HomingRequest Request;
typedef HomingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Homing
} // namespace neo_kinematics_omnidrive


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neo_kinematics_omnidrive::Homing > {
  static const char* value()
  {
    return "5f31cb2e813cfb0e488c574c3b5d9dbe";
  }

  static const char* value(const ::neo_kinematics_omnidrive::Homing&) { return value(); }
};

template<>
struct DataType< ::neo_kinematics_omnidrive::Homing > {
  static const char* value()
  {
    return "neo_kinematics_omnidrive/Homing";
  }

  static const char* value(const ::neo_kinematics_omnidrive::Homing&) { return value(); }
};


// service_traits::MD5Sum< ::neo_kinematics_omnidrive::HomingRequest> should match 
// service_traits::MD5Sum< ::neo_kinematics_omnidrive::Homing > 
template<>
struct MD5Sum< ::neo_kinematics_omnidrive::HomingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neo_kinematics_omnidrive::Homing >::value();
  }
  static const char* value(const ::neo_kinematics_omnidrive::HomingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_kinematics_omnidrive::HomingRequest> should match 
// service_traits::DataType< ::neo_kinematics_omnidrive::Homing > 
template<>
struct DataType< ::neo_kinematics_omnidrive::HomingRequest>
{
  static const char* value()
  {
    return DataType< ::neo_kinematics_omnidrive::Homing >::value();
  }
  static const char* value(const ::neo_kinematics_omnidrive::HomingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neo_kinematics_omnidrive::HomingResponse> should match 
// service_traits::MD5Sum< ::neo_kinematics_omnidrive::Homing > 
template<>
struct MD5Sum< ::neo_kinematics_omnidrive::HomingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neo_kinematics_omnidrive::Homing >::value();
  }
  static const char* value(const ::neo_kinematics_omnidrive::HomingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neo_kinematics_omnidrive::HomingResponse> should match 
// service_traits::DataType< ::neo_kinematics_omnidrive::Homing > 
template<>
struct DataType< ::neo_kinematics_omnidrive::HomingResponse>
{
  static const char* value()
  {
    return DataType< ::neo_kinematics_omnidrive::Homing >::value();
  }
  static const char* value(const ::neo_kinematics_omnidrive::HomingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEO_KINEMATICS_OMNIDRIVE_MESSAGE_HOMING_H
